-- Create admin role

CREATE ROLE admin_role
WITH LOGIN
PASSWORD "admin123"
SUPERUSER
CREATEDB
CREATEROLE;


--  Grant privilege for admin_role

GRANT CONNECT ON DATABASE exam_db TO admin_role;

GRANT USAGE ON SCHEMA public TO admin_role;

GRANT SELECT, INSERT, UPDATE, DELETE
ON ALL TABLES IN SCHEMA public
TO admin_role;


ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT SELECT, INSERT, UPDATE, DELETE
ON TABLES TO admin_role;

